### ISSUE TITLE
Standardiser hangs during use 

### ISSUE THREAD

**Issue by 0xln** [Acceis/leakScraper#4]
I’m trying to troubleshoot an issue with the script hanging on unexpected characters. 

I originally identified control characters causing problems, so have been stripping those out of my input files, but I’m still getting problems. Is there a debug mode to indicate which strings it crashed on ? 

I will start collecting examples of the strings that are crashing now it

**Comment by almandin** [comment]
Hello, I don't have much time now to look at this but I'll try to do my best.
Checking for unexpected characters was already quite a pain. There's already a try/catch to check for non-utf8 characters but I understand that control characters are utf-8 compliant, ther are just not printable :-)

**Comment by 0xln** [comment]
No worries, i'm asking a friend to take a look as well to help solve the issue too

**Comment by 0xln** [comment]
Mostly looks like the issue is in the posix regex

**Comment by almandin** [comment]
I used to find a dos (denial of service) issue in the posix regex back to when I wrote the initial code of fuxploider. The problem was when emails had a lot of dots at the end of the left part, like 'somebody..........@somewhere.com' . I started having the standardizer hanging and found out this problem. I even measured the problem and found that the time the regex would need was exponentially increased by the number of dots ! There might be other problems with this regex. I don't plan to change it or remove it, so if it appears that it's the regex, just let me know and I'll close the issue.
